name: FastAPI CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    env:
      MODE: "dev"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      TAVILY_API_KEY: ${{secrets.TAVILY_API_KEY}}
      STORAGE_BUCKET: ${{secrets.STORAGE_BUCKET}}
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{vars.FIREBASE_JSON_PATH}}

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Debug Check Directory
        run: |
          pwd
          mkdir -p secrets
      - name: Decode Firebase credentials
        run: |
          mkdir -p secrets
          echo '${{ secrets.FIREBASE_JSON }}' > ${{vars.FIREBASE_JSON_PATH}}
          cd secrets
          ls -l

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

        working-directory: ./backend

      - name: Install dependencies
        run: poetry install
        working-directory: ./backend

      - name: Run Test
        run: |
          poetry run python -m pytest -s --log-cli-level=INFO
        working-directory: ./backend
